spring:
    application:
        name: activity-ui
    thymeleaf:
        mode: LEGACYHTML5
        cache: false
server:
    port: 32106
eureka:
    instance:
      prefer-ip-address: true

ht.config.ui:
  gatewayUrl: http://172.16.200.115:30111/
  changePwdUrl: http://172.16.200.115:30131/html/user/changePwdOther.html
  userInfoUpdate: http://172.16.200.115:30131/html/user/userInfoOther.html
  localGatewayUrl: http://172.16.200.115:30111/activity/service/
